### ISSUE TITLE
We need a way to calculate a value to represent the growth of a repository over a given month

### ISSUE THREAD

**Issue by 371student** [371student/SENG371Project#2]

**Comment by lamjwe** [comment]
Group @guand @paulmoon @lamj1234
Lines of Code of a repository can help you calculate the growth of a repository overtime. 
You can go to the "Graphs" section of the repo. Then click "Code Frequency." This displays the number lines of code that is added and deleted overtime.  
Or
Try [git-loc](https://github.com/ITikhonov/git-loc). This shows the LOC of a repository overtime.

**Comment by Brayden-Arthur** [comment]
If you aren't already gitstats does show the number of commits by month/year as well as the number of lines added and removed. You could use that with the overall size of the project to relate its growth that month.

**Comment by devinc13** [comment]
It might not be exactly what you're looking for, but we made a python script that hits the github API in monthly increments, and can search issues and pull requests on a monthly basis. Might be helpful?
https://github.com/devinc13/SENG371-Devin-and-Andrew
There are notes on the script's usage in the readme.
